export const normalized: Record<number, string> = {
  0x00e1: "a", //  WITH ACUTE, LATIN SMALL LETTER
  0x0103: "a", //  WITH BREVE, LATIN SMALL LETTER
  0x01ce: "a", //  WITH CARON, LATIN SMALL LETTER
  0x00e2: "a", //  WITH CIRCUMFLEX, LATIN SMALL LETTER
  0x00e4: "a", //  WITH DIAERESIS, LATIN SMALL LETTER
  0x0227: "a", //  WITH DOT ABOVE, LATIN SMALL LETTER
  0x1ea1: "a", //  WITH DOT BELOW, LATIN SMALL LETTER
  0x0201: "a", //  WITH DOUBLE GRAVE, LATIN SMALL LETTER
  0x00e0: "a", //  WITH GRAVE, LATIN SMALL LETTER
  0x1ea3: "a", //  WITH HOOK ABOVE, LATIN SMALL LETTER
  0x0203: "a", //  WITH INVERTED BREVE, LATIN SMALL LETTER
  0x0101: "a", //  WITH MACRON, LATIN SMALL LETTER
  0x0105: "a", //  WITH OGONEK, LATIN SMALL LETTER
  0x1e9a: "a", //  WITH RIGHT HALF RING, LATIN SMALL LETTER
  0x00e5: "a", //  WITH RING ABOVE, LATIN SMALL LETTER
  0x1e01: "a", //  WITH RING BELOW, LATIN SMALL LETTER
  0x00e3: "a", //  WITH TILDE, LATIN SMALL LETTER
  0x0363: "a", // , COMBINING LATIN SMALL LETTER
  0x0250: "a", // , LATIN SMALL LETTER TURNED
  0x1e03: "b", //  WITH DOT ABOVE, LATIN SMALL LETTER
  0x1e05: "b", //  WITH DOT BELOW, LATIN SMALL LETTER
  0x0253: "b", //  WITH HOOK, LATIN SMALL LETTER
  0x1e07: "b", //  WITH LINE BELOW, LATIN SMALL LETTER
  0x0180: "b", //  WITH STROKE, LATIN SMALL LETTER
  0x0183: "b", //  WITH TOPBAR, LATIN SMALL LETTER
  0x0107: "c", //  WITH ACUTE, LATIN SMALL LETTER
  0x010d: "c", //  WITH CARON, LATIN SMALL LETTER
  0x00e7: "c", //  WITH CEDILLA, LATIN SMALL LETTER
  0x0109: "c", //  WITH CIRCUMFLEX, LATIN SMALL LETTER
  0x0255: "c", //  WITH CURL, LATIN SMALL LETTER
  0x010b: "c", //  WITH DOT ABOVE, LATIN SMALL LETTER
  0x0188: "c", //  WITH HOOK, LATIN SMALL LETTER
  0x023c: "c", //  WITH STROKE, LATIN SMALL LETTER
  0x0368: "c", // , COMBINING LATIN SMALL LETTER
  0x0297: "c", // , LATIN LETTER STRETCHED
  0x2184: "c", // , LATIN SMALL LETTER REVERSED
  0x010f: "d", //  WITH CARON, LATIN SMALL LETTER
  0x1e11: "d", //  WITH CEDILLA, LATIN SMALL LETTER
  0x1e13: "d", //  WITH CIRCUMFLEX BELOW, LATIN SMALL LETTER
  0x0221: "d", //  WITH CURL, LATIN SMALL LETTER
  0x1e0b: "d", //  WITH DOT ABOVE, LATIN SMALL LETTER
  0x1e0d: "d", //  WITH DOT BELOW, LATIN SMALL LETTER
  0x0257: "d", //  WITH HOOK, LATIN SMALL LETTER
  0x1e0f: "d", //  WITH LINE BELOW, LATIN SMALL LETTER
  0x0111: "d", //  WITH STROKE, LATIN SMALL LETTER
  0x0256: "d", //  WITH TAIL, LATIN SMALL LETTER
  0x018c: "d", //  WITH TOPBAR, LATIN SMALL LETTER
  0x0369: "d", // , COMBINING LATIN SMALL LETTER
  0x00e9: "e", //  WITH ACUTE, LATIN SMALL LETTER
  0x0115: "e", //  WITH BREVE, LATIN SMALL LETTER
  0x011b: "e", //  WITH CARON, LATIN SMALL LETTER
  0x0229: "e", //  WITH CEDILLA, LATIN SMALL LETTER
  0x1e19: "e", //  WITH CIRCUMFLEX BELOW, LATIN SMALL LETTER
  0x00ea: "e", //  WITH CIRCUMFLEX, LATIN SMALL LETTER
  0x00eb: "e", //  WITH DIAERESIS, LATIN SMALL LETTER
  0x0117: "e", //  WITH DOT ABOVE, LATIN SMALL LETTER
  0x1eb9: "e", //  WITH DOT BELOW, LATIN SMALL LETTER
  0x0205: "e", //  WITH DOUBLE GRAVE, LATIN SMALL LETTER
  0x00e8: "e", //  WITH GRAVE, LATIN SMALL LETTER
  0x1ebb: "e", //  WITH HOOK ABOVE, LATIN SMALL LETTER
  0x025d: "e", //  WITH HOOK, LATIN SMALL LETTER REVERSED OPEN
  0x0207: "e", //  WITH INVERTED BREVE, LATIN SMALL LETTER
  0x0113: "e", //  WITH MACRON, LATIN SMALL LETTER
  0x0119: "e", //  WITH OGONEK, LATIN SMALL LETTER
  0x0247: "e", //  WITH STROKE, LATIN SMALL LETTER
  0x1e1b: "e", //  WITH TILDE BELOW, LATIN SMALL LETTER
  0x1ebd: "e", //  WITH TILDE, LATIN SMALL LETTER
  0x0364: "e", // , COMBINING LATIN SMALL LETTER
  0x029a: "e", // , LATIN SMALL LETTER CLOSED OPEN
  0x025e: "e", // , LATIN SMALL LETTER CLOSED REVERSED OPEN
  0x025b: "e", // , LATIN SMALL LETTER OPEN
  0x0258: "e", // , LATIN SMALL LETTER REVERSED
  0x025c: "e", // , LATIN SMALL LETTER REVERSED OPEN
  0x01dd: "e", // , LATIN SMALL LETTER TURNED
  0x1d08: "e", // , LATIN SMALL LETTER TURNED OPEN
  0x1e1f: "f", //  WITH DOT ABOVE, LATIN SMALL LETTER
  0x0192: "f", //  WITH HOOK, LATIN SMALL LETTER
  0x01f5: "g", //  WITH ACUTE, LATIN SMALL LETTER
  0x011f: "g", //  WITH BREVE, LATIN SMALL LETTER
  0x01e7: "g", //  WITH CARON, LATIN SMALL LETTER
  0x0123: "g", //  WITH CEDILLA, LATIN SMALL LETTER
  0x011d: "g", //  WITH CIRCUMFLEX, LATIN SMALL LETTER
  0x0121: "g", //  WITH DOT ABOVE, LATIN SMALL LETTER
  0x0260: "g", //  WITH HOOK, LATIN SMALL LETTER
  0x1e21: "g", //  WITH MACRON, LATIN SMALL LETTER
  0x01e5: "g", //  WITH STROKE, LATIN SMALL LETTER
  0x0261: "g", // , LATIN SMALL LETTER SCRIPT
  0x1e2b: "h", //  WITH BREVE BELOW, LATIN SMALL LETTER
  0x021f: "h", //  WITH CARON, LATIN SMALL LETTER
  0x1e29: "h", //  WITH CEDILLA, LATIN SMALL LETTER
  0x0125: "h", //  WITH CIRCUMFLEX, LATIN SMALL LETTER
  0x1e27: "h", //  WITH DIAERESIS, LATIN SMALL LETTER
  0x1e23: "h", //  WITH DOT ABOVE, LATIN SMALL LETTER
  0x1e25: "h", //  WITH DOT BELOW, LATIN SMALL LETTER
  0x02ae: "h", //  WITH FISHHOOK, LATIN SMALL LETTER TURNED
  0x0266: "h", //  WITH HOOK, LATIN SMALL LETTER
  0x1e96: "h", //  WITH LINE BELOW, LATIN SMALL LETTER
  0x0127: "h", //  WITH STROKE, LATIN SMALL LETTER
  0x036a: "h", // , COMBINING LATIN SMALL LETTER
  0x0265: "h", // , LATIN SMALL LETTER TURNED
  0x2095: "h", // , LATIN SUBSCRIPT SMALL LETTER
  0x00ed: "i", //  WITH ACUTE, LATIN SMALL LETTER
  0x012d: "i", //  WITH BREVE, LATIN SMALL LETTER
  0x01d0: "i", //  WITH CARON, LATIN SMALL LETTER
  0x00ee: "i", //  WITH CIRCUMFLEX, LATIN SMALL LETTER
  0x00ef: "i", //  WITH DIAERESIS, LATIN SMALL LETTER
  0x1ecb: "i", //  WITH DOT BELOW, LATIN SMALL LETTER
  0x0209: "i", //  WITH DOUBLE GRAVE, LATIN SMALL LETTER
  0x00ec: "i", //  WITH GRAVE, LATIN SMALL LETTER
  0x1ec9: "i", //  WITH HOOK ABOVE, LATIN SMALL LETTER
  0x020b: "i", //  WITH INVERTED BREVE, LATIN SMALL LETTER
  0x012b: "i", //  WITH MACRON, LATIN SMALL LETTER
  0x012f: "i", //  WITH OGONEK, LATIN SMALL LETTER
  0x0268: "i", //  WITH STROKE, LATIN SMALL LETTER
  0x1e2d: "i", //  WITH TILDE BELOW, LATIN SMALL LETTER
  0x0129: "i", //  WITH TILDE, LATIN SMALL LETTER
  0x0365: "i", // , COMBINING LATIN SMALL LETTER
  0x0131: "i", // , LATIN SMALL LETTER DOTLESS
  0x1d09: "i", // , LATIN SMALL LETTER TURNED
  0x1d62: "i", // , LATIN SUBSCRIPT SMALL LETTER
  0x2071: "i", // , SUPERSCRIPT LATIN SMALL LETTER
  0x01f0: "j", //  WITH CARON, LATIN SMALL LETTER
  0x0135: "j", //  WITH CIRCUMFLEX, LATIN SMALL LETTER
  0x029d: "j", //  WITH CROSSED-TAIL, LATIN SMALL LETTER
  0x0249: "j", //  WITH STROKE, LATIN SMALL LETTER
  0x025f: "j", //  WITH STROKE, LATIN SMALL LETTER DOTLESS
  0x0237: "j", // , LATIN SMALL LETTER DOTLESS
  0x1e31: "k", //  WITH ACUTE, LATIN SMALL LETTER
  0x01e9: "k", //  WITH CARON, LATIN SMALL LETTER
  0x0137: "k", //  WITH CEDILLA, LATIN SMALL LETTER
  0x1e33: "k", //  WITH DOT BELOW, LATIN SMALL LETTER
  0x0199: "k", //  WITH HOOK, LATIN SMALL LETTER
  0x1e35: "k", //  WITH LINE BELOW, LATIN SMALL LETTER
  0x029e: "k", // , LATIN SMALL LETTER TURNED
  0x2096: "k", // , LATIN SUBSCRIPT SMALL LETTER
  0x013a: "l", //  WITH ACUTE, LATIN SMALL LETTER
  0x019a: "l", //  WITH BAR, LATIN SMALL LETTER
  0x026c: "l", //  WITH BELT, LATIN SMALL LETTER
  0x013e: "l", //  WITH CARON, LATIN SMALL LETTER
  0x013c: "l", //  WITH CEDILLA, LATIN SMALL LETTER
  0x1e3d: "l", //  WITH CIRCUMFLEX BELOW, LATIN SMALL LETTER
  0x0234: "l", //  WITH CURL, LATIN SMALL LETTER
  0x1e37: "l", //  WITH DOT BELOW, LATIN SMALL LETTER
  0x1e3b: "l", //  WITH LINE BELOW, LATIN SMALL LETTER
  0x0140: "l", //  WITH MIDDLE DOT, LATIN SMALL LETTER
  0x026b: "l", //  WITH MIDDLE TILDE, LATIN SMALL LETTER
  0x026d: "l", //  WITH RETROFLEX HOOK, LATIN SMALL LETTER
  0x0142: "l", //  WITH STROKE, LATIN SMALL LETTER
  0x2097: "l", // , LATIN SUBSCRIPT SMALL LETTER
  0x1e3f: "m", //  WITH ACUTE, LATIN SMALL LETTER
  0x1e41: "m", //  WITH DOT ABOVE, LATIN SMALL LETTER
  0x1e43: "m", //  WITH DOT BELOW, LATIN SMALL LETTER
  0x0271: "m", //  WITH HOOK, LATIN SMALL LETTER
  0x0270: "m", //  WITH LONG LEG, LATIN SMALL LETTER TURNED
  0x036b: "m", // , COMBINING LATIN SMALL LETTER
  0x1d1f: "m", // , LATIN SMALL LETTER SIDEWAYS TURNED
  0x026f: "m", // , LATIN SMALL LETTER TURNED
  0x2098: "m", // , LATIN SUBSCRIPT SMALL LETTER
  0x0144: "n", //  WITH ACUTE, LATIN SMALL LETTER
  0x0148: "n", //  WITH CARON, LATIN SMALL LETTER
  0x0146: "n", //  WITH CEDILLA, LATIN SMALL LETTER
  0x1e4b: "n", //  WITH CIRCUMFLEX BELOW, LATIN SMALL LETTER
  0x0235: "n", //  WITH CURL, LATIN SMALL LETTER
  0x1e45: "n", //  WITH DOT ABOVE, LATIN SMALL LETTER
  0x1e47: "n", //  WITH DOT BELOW, LATIN SMALL LETTER
  0x01f9: "n", //  WITH GRAVE, LATIN SMALL LETTER
  0x0272: "n", //  WITH LEFT HOOK, LATIN SMALL LETTER
  0x1e49: "n", //  WITH LINE BELOW, LATIN SMALL LETTER
  0x019e: "n", //  WITH LONG RIGHT LEG, LATIN SMALL LETTER
  0x0273: "n", //  WITH RETROFLEX HOOK, LATIN SMALL LETTER
  0x00f1: "n", //  WITH TILDE, LATIN SMALL LETTER
  0x2099: "n", // , LATIN SUBSCRIPT SMALL LETTER
  0x00f3: "o", //  WITH ACUTE, LATIN SMALL LETTER
  0x014f: "o", //  WITH BREVE, LATIN SMALL LETTER
  0x01d2: "o", //  WITH CARON, LATIN SMALL LETTER
  0x00f4: "o", //  WITH CIRCUMFLEX, LATIN SMALL LETTER
  0x00f6: "o", //  WITH DIAERESIS, LATIN SMALL LETTER
  0x022f: "o", //  WITH DOT ABOVE, LATIN SMALL LETTER
  0x1ecd: "o", //  WITH DOT BELOW, LATIN SMALL LETTER
  0x0151: "o", //  WITH DOUBLE ACUTE, LATIN SMALL LETTER
  0x020d: "o", //  WITH DOUBLE GRAVE, LATIN SMALL LETTER
  0x00f2: "o", //  WITH GRAVE, LATIN SMALL LETTER
  0x1ecf: "o", //  WITH HOOK ABOVE, LATIN SMALL LETTER
  0x01a1: "o", //  WITH HORN, LATIN SMALL LETTER
  0x020f: "o", //  WITH INVERTED BREVE, LATIN SMALL LETTER
  0x014d: "o", //  WITH MACRON, LATIN SMALL LETTER
  0x01eb: "o", //  WITH OGONEK, LATIN SMALL LETTER
  0x00f8: "o", //  WITH STROKE, LATIN SMALL LETTER
  0x1d13: "o", //  WITH STROKE, LATIN SMALL LETTER SIDEWAYS
  0x00f5: "o", //  WITH TILDE, LATIN SMALL LETTER
  0x0366: "o", // , COMBINING LATIN SMALL LETTER
  0x0275: "o", // , LATIN SMALL LETTER BARRED
  0x1d17: "o", // , LATIN SMALL LETTER BOTTOM HALF
  0x0254: "o", // , LATIN SMALL LETTER OPEN
  0x1d11: "o", // , LATIN SMALL LETTER SIDEWAYS
  0x1d12: "o", // , LATIN SMALL LETTER SIDEWAYS OPEN
  0x1d16: "o", // , LATIN SMALL LETTER TOP HALF
  0x1e55: "p", //  WITH ACUTE, LATIN SMALL LETTER
  0x1e57: "p", //  WITH DOT ABOVE, LATIN SMALL LETTER
  0x01a5: "p", //  WITH HOOK, LATIN SMALL LETTER
  0x209a: "p", // , LATIN SUBSCRIPT SMALL LETTER
  0x024b: "q", //  WITH HOOK TAIL, LATIN SMALL LETTER
  0x02a0: "q", //  WITH HOOK, LATIN SMALL LETTER
  0x0155: "r", //  WITH ACUTE, LATIN SMALL LETTER
  0x0159: "r", //  WITH CARON, LATIN SMALL LETTER
  0x0157: "r", //  WITH CEDILLA, LATIN SMALL LETTER
  0x1e59: "r", //  WITH DOT ABOVE, LATIN SMALL LETTER
  0x1e5b: "r", //  WITH DOT BELOW, LATIN SMALL LETTER
  0x0211: "r", //  WITH DOUBLE GRAVE, LATIN SMALL LETTER
  0x027e: "r", //  WITH FISHHOOK, LATIN SMALL LETTER
  0x027f: "r", //  WITH FISHHOOK, LATIN SMALL LETTER REVERSED
  0x027b: "r", //  WITH HOOK, LATIN SMALL LETTER TURNED
  0x0213: "r", //  WITH INVERTED BREVE, LATIN SMALL LETTER
  0x1e5f: "r", //  WITH LINE BELOW, LATIN SMALL LETTER
  0x027c: "r", //  WITH LONG LEG, LATIN SMALL LETTER
  0x027a: "r", //  WITH LONG LEG, LATIN SMALL LETTER TURNED
  0x024d: "r", //  WITH STROKE, LATIN SMALL LETTER
  0x027d: "r", //  WITH TAIL, LATIN SMALL LETTER
  0x036c: "r", // , COMBINING LATIN SMALL LETTER
  0x0279: "r", // , LATIN SMALL LETTER TURNED
  0x1d63: "r", // , LATIN SUBSCRIPT SMALL LETTER
  0x015b: "s", //  WITH ACUTE, LATIN SMALL LETTER
  0x0161: "s", //  WITH CARON, LATIN SMALL LETTER
  0x015f: "s", //  WITH CEDILLA, LATIN SMALL LETTER
  0x015d: "s", //  WITH CIRCUMFLEX, LATIN SMALL LETTER
  0x0219: "s", //  WITH COMMA BELOW, LATIN SMALL LETTER
  0x1e61: "s", //  WITH DOT ABOVE, LATIN SMALL LETTER
  0x1e9b: "s", //  WITH DOT ABOVE, LATIN SMALL LETTER LONG
  0x1e63: "s", //  WITH DOT BELOW, LATIN SMALL LETTER
  0x0282: "s", //  WITH HOOK, LATIN SMALL LETTER
  0x023f: "s", //  WITH SWASH TAIL, LATIN SMALL LETTER
  0x017f: "s", // , LATIN SMALL LETTER LONG
  0x00df: "s", // , LATIN SMALL LETTER SHARP
  0x209b: "s", // , LATIN SUBSCRIPT SMALL LETTER
  0x0165: "t", //  WITH CARON, LATIN SMALL LETTER
  0x0163: "t", //  WITH CEDILLA, LATIN SMALL LETTER
  0x1e71: "t", //  WITH CIRCUMFLEX BELOW, LATIN SMALL LETTER
  0x021b: "t", //  WITH COMMA BELOW, LATIN SMALL LETTER
  0x0236: "t", //  WITH CURL, LATIN SMALL LETTER
  0x1e97: "t", //  WITH DIAERESIS, LATIN SMALL LETTER
  0x1e6b: "t", //  WITH DOT ABOVE, LATIN SMALL LETTER
  0x1e6d: "t", //  WITH DOT BELOW, LATIN SMALL LETTER
  0x01ad: "t", //  WITH HOOK, LATIN SMALL LETTER
  0x1e6f: "t", //  WITH LINE BELOW, LATIN SMALL LETTER
  0x01ab: "t", //  WITH PALATAL HOOK, LATIN SMALL LETTER
  0x0288: "t", //  WITH RETROFLEX HOOK, LATIN SMALL LETTER
  0x0167: "t", //  WITH STROKE, LATIN SMALL LETTER
  0x036d: "t", // , COMBINING LATIN SMALL LETTER
  0x0287: "t", // , LATIN SMALL LETTER TURNED
  0x209c: "t", // , LATIN SUBSCRIPT SMALL LETTER
  0x0289: "u", //  BAR, LATIN SMALL LETTER
  0x00fa: "u", //  WITH ACUTE, LATIN SMALL LETTER
  0x016d: "u", //  WITH BREVE, LATIN SMALL LETTER
  0x01d4: "u", //  WITH CARON, LATIN SMALL LETTER
  0x1e77: "u", //  WITH CIRCUMFLEX BELOW, LATIN SMALL LETTER
  0x00fb: "u", //  WITH CIRCUMFLEX, LATIN SMALL LETTER
  0x1e73: "u", //  WITH DIAERESIS BELOW, LATIN SMALL LETTER
  0x00fc: "u", //  WITH DIAERESIS, LATIN SMALL LETTER
  0x1ee5: "u", //  WITH DOT BELOW, LATIN SMALL LETTER
  0x0171: "u", //  WITH DOUBLE ACUTE, LATIN SMALL LETTER
  0x0215: "u", //  WITH DOUBLE GRAVE, LATIN SMALL LETTER
  0x00f9: "u", //  WITH GRAVE, LATIN SMALL LETTER
  0x1ee7: "u", //  WITH HOOK ABOVE, LATIN SMALL LETTER
  0x01b0: "u", //  WITH HORN, LATIN SMALL LETTER
  0x0217: "u", //  WITH INVERTED BREVE, LATIN SMALL LETTER
  0x016b: "u", //  WITH MACRON, LATIN SMALL LETTER
  0x0173: "u", //  WITH OGONEK, LATIN SMALL LETTER
  0x016f: "u", //  WITH RING ABOVE, LATIN SMALL LETTER
  0x1e75: "u", //  WITH TILDE BELOW, LATIN SMALL LETTER
  0x0169: "u", //  WITH TILDE, LATIN SMALL LETTER
  0x0367: "u", // , COMBINING LATIN SMALL LETTER
  0x1d1d: "u", // , LATIN SMALL LETTER SIDEWAYS
  0x1d1e: "u", // , LATIN SMALL LETTER SIDEWAYS DIAERESIZED
  0x1d64: "u", // , LATIN SUBSCRIPT SMALL LETTER
  0x1e7f: "v", //  WITH DOT BELOW, LATIN SMALL LETTER
  0x028b: "v", //  WITH HOOK, LATIN SMALL LETTER
  0x1e7d: "v", //  WITH TILDE, LATIN SMALL LETTER
  0x036e: "v", // , COMBINING LATIN SMALL LETTER
  0x028c: "v", // , LATIN SMALL LETTER TURNED
  0x1d65: "v", // , LATIN SUBSCRIPT SMALL LETTER
  0x1e83: "w", //  WITH ACUTE, LATIN SMALL LETTER
  0x0175: "w", //  WITH CIRCUMFLEX, LATIN SMALL LETTER
  0x1e85: "w", //  WITH DIAERESIS, LATIN SMALL LETTER
  0x1e87: "w", //  WITH DOT ABOVE, LATIN SMALL LETTER
  0x1e89: "w", //  WITH DOT BELOW, LATIN SMALL LETTER
  0x1e81: "w", //  WITH GRAVE, LATIN SMALL LETTER
  0x1e98: "w", //  WITH RING ABOVE, LATIN SMALL LETTER
  0x028d: "w", // , LATIN SMALL LETTER TURNED
  0x1e8d: "x", //  WITH DIAERESIS, LATIN SMALL LETTER
  0x1e8b: "x", //  WITH DOT ABOVE, LATIN SMALL LETTER
  0x036f: "x", // , COMBINING LATIN SMALL LETTER
  0x00fd: "y", //  WITH ACUTE, LATIN SMALL LETTER
  0x0177: "y", //  WITH CIRCUMFLEX, LATIN SMALL LETTER
  0x00ff: "y", //  WITH DIAERESIS, LATIN SMALL LETTER
  0x1e8f: "y", //  WITH DOT ABOVE, LATIN SMALL LETTER
  0x1ef5: "y", //  WITH DOT BELOW, LATIN SMALL LETTER
  0x1ef3: "y", //  WITH GRAVE, LATIN SMALL LETTER
  0x1ef7: "y", //  WITH HOOK ABOVE, LATIN SMALL LETTER
  0x01b4: "y", //  WITH HOOK, LATIN SMALL LETTER
  0x0233: "y", //  WITH MACRON, LATIN SMALL LETTER
  0x1e99: "y", //  WITH RING ABOVE, LATIN SMALL LETTER
  0x024f: "y", //  WITH STROKE, LATIN SMALL LETTER
  0x1ef9: "y", //  WITH TILDE, LATIN SMALL LETTER
  0x028e: "y", // , LATIN SMALL LETTER TURNED
  0x017a: "z", //  WITH ACUTE, LATIN SMALL LETTER
  0x017e: "z", //  WITH CARON, LATIN SMALL LETTER
  0x1e91: "z", //  WITH CIRCUMFLEX, LATIN SMALL LETTER
  0x0291: "z", //  WITH CURL, LATIN SMALL LETTER
  0x017c: "z", //  WITH DOT ABOVE, LATIN SMALL LETTER
  0x1e93: "z", //  WITH DOT BELOW, LATIN SMALL LETTER
  0x0225: "z", //  WITH HOOK, LATIN SMALL LETTER
  0x1e95: "z", //  WITH LINE BELOW, LATIN SMALL LETTER
  0x0290: "z", //  WITH RETROFLEX HOOK, LATIN SMALL LETTER
  0x01b6: "z", //  WITH STROKE, LATIN SMALL LETTER
  0x0240: "z", //  WITH SWASH TAIL, LATIN SMALL LETTER
  0x0251: "a", // , latin small letter script
  0x00c1: "A", //  WITH ACUTE, LATIN CAPITAL LETTER
  0x00c2: "A", //  WITH CIRCUMFLEX, LATIN CAPITAL LETTER
  0x00c4: "A", //  WITH DIAERESIS, LATIN CAPITAL LETTER
  0x00c0: "A", //  WITH GRAVE, LATIN CAPITAL LETTER
  0x00c5: "A", //  WITH RING ABOVE, LATIN CAPITAL LETTER
  0x023a: "A", //  WITH STROKE, LATIN CAPITAL LETTER
  0x00c3: "A", //  WITH TILDE, LATIN CAPITAL LETTER
  0x1d00: "A", // , LATIN LETTER SMALL CAPITAL
  0x0181: "B", //  WITH HOOK, LATIN CAPITAL LETTER
  0x0243: "B", //  WITH STROKE, LATIN CAPITAL LETTER
  0x0299: "B", // , LATIN LETTER SMALL CAPITAL
  0x1d03: "B", // , LATIN LETTER SMALL CAPITAL BARRED
  0x00c7: "C", //  WITH CEDILLA, LATIN CAPITAL LETTER
  0x023b: "C", //  WITH STROKE, LATIN CAPITAL LETTER
  0x1d04: "C", // , LATIN LETTER SMALL CAPITAL
  0x018a: "D", //  WITH HOOK, LATIN CAPITAL LETTER
  0x0189: "D", // , LATIN CAPITAL LETTER AFRICAN
  0x1d05: "D", // , LATIN LETTER SMALL CAPITAL
  0x00c9: "E", //  WITH ACUTE, LATIN CAPITAL LETTER
  0x00ca: "E", //  WITH CIRCUMFLEX, LATIN CAPITAL LETTER
  0x00cb: "E", //  WITH DIAERESIS, LATIN CAPITAL LETTER
  0x00c8: "E", //  WITH GRAVE, LATIN CAPITAL LETTER
  0x0246: "E", //  WITH STROKE, LATIN CAPITAL LETTER
  0x0190: "E", // , LATIN CAPITAL LETTER OPEN
  0x018e: "E", // , LATIN CAPITAL LETTER REVERSED
  0x1d07: "E", // , LATIN LETTER SMALL CAPITAL
  0x0193: "G", //  WITH HOOK, LATIN CAPITAL LETTER
  0x029b: "G", //  WITH HOOK, LATIN LETTER SMALL CAPITAL
  0x0262: "G", // , LATIN LETTER SMALL CAPITAL
  0x029c: "H", // , LATIN LETTER SMALL CAPITAL
  0x00cd: "I", //  WITH ACUTE, LATIN CAPITAL LETTER
  0x00ce: "I", //  WITH CIRCUMFLEX, LATIN CAPITAL LETTER
  0x00cf: "I", //  WITH DIAERESIS, LATIN CAPITAL LETTER
  0x0130: "I", //  WITH DOT ABOVE, LATIN CAPITAL LETTER
  0x00cc: "I", //  WITH GRAVE, LATIN CAPITAL LETTER
  0x0197: "I", //  WITH STROKE, LATIN CAPITAL LETTER
  0x026a: "I", // , LATIN LETTER SMALL CAPITAL
  0x0248: "J", //  WITH STROKE, LATIN CAPITAL LETTER
  0x1d0a: "J", // , LATIN LETTER SMALL CAPITAL
  0x1d0b: "K", // , LATIN LETTER SMALL CAPITAL
  0x023d: "L", //  WITH BAR, LATIN CAPITAL LETTER
  0x1d0c: "L", //  WITH STROKE, LATIN LETTER SMALL CAPITAL
  0x029f: "L", // , LATIN LETTER SMALL CAPITAL
  0x019c: "M", // , LATIN CAPITAL LETTER TURNED
  0x1d0d: "M", // , LATIN LETTER SMALL CAPITAL
  0x019d: "N", //  WITH LEFT HOOK, LATIN CAPITAL LETTER
  0x0220: "N", //  WITH LONG RIGHT LEG, LATIN CAPITAL LETTER
  0x00d1: "N", //  WITH TILDE, LATIN CAPITAL LETTER
  0x0274: "N", // , LATIN LETTER SMALL CAPITAL
  0x1d0e: "N", // , LATIN LETTER SMALL CAPITAL REVERSED
  0x00d3: "O", //  WITH ACUTE, LATIN CAPITAL LETTER
  0x00d4: "O", //  WITH CIRCUMFLEX, LATIN CAPITAL LETTER
  0x00d6: "O", //  WITH DIAERESIS, LATIN CAPITAL LETTER
  0x00d2: "O", //  WITH GRAVE, LATIN CAPITAL LETTER
  0x019f: "O", //  WITH MIDDLE TILDE, LATIN CAPITAL LETTER
  0x00d8: "O", //  WITH STROKE, LATIN CAPITAL LETTER
  0x00d5: "O", //  WITH TILDE, LATIN CAPITAL LETTER
  0x0186: "O", // , LATIN CAPITAL LETTER OPEN
  0x1d0f: "O", // , LATIN LETTER SMALL CAPITAL
  0x1d10: "O", // , LATIN LETTER SMALL CAPITAL OPEN
  0x1d18: "P", // , LATIN LETTER SMALL CAPITAL
  0x024a: "Q", //  WITH HOOK TAIL, LATIN CAPITAL LETTER SMALL
  0x024c: "R", //  WITH STROKE, LATIN CAPITAL LETTER
  0x0280: "R", // , LATIN LETTER SMALL CAPITAL
  0x0281: "R", // , LATIN LETTER SMALL CAPITAL INVERTED
  0x1d19: "R", // , LATIN LETTER SMALL CAPITAL REVERSED
  0x1d1a: "R", // , LATIN LETTER SMALL CAPITAL TURNED
  0x023e: "T", //  WITH DIAGONAL STROKE, LATIN CAPITAL LETTER
  0x01ae: "T", //  WITH RETROFLEX HOOK, LATIN CAPITAL LETTER
  0x1d1b: "T", // , LATIN LETTER SMALL CAPITAL
  0x0244: "U", //  BAR, LATIN CAPITAL LETTER
  0x00da: "U", //  WITH ACUTE, LATIN CAPITAL LETTER
  0x00db: "U", //  WITH CIRCUMFLEX, LATIN CAPITAL LETTER
  0x00dc: "U", //  WITH DIAERESIS, LATIN CAPITAL LETTER
  0x00d9: "U", //  WITH GRAVE, LATIN CAPITAL LETTER
  0x1d1c: "U", // , LATIN LETTER SMALL CAPITAL
  0x01b2: "V", //  WITH HOOK, LATIN CAPITAL LETTER
  0x0245: "V", // , LATIN CAPITAL LETTER TURNED
  0x1d20: "V", // , LATIN LETTER SMALL CAPITAL
  0x1d21: "W", // , LATIN LETTER SMALL CAPITAL
  0x00dd: "Y", //  WITH ACUTE, LATIN CAPITAL LETTER
  0x0178: "Y", //  WITH DIAERESIS, LATIN CAPITAL LETTER
  0x024e: "Y", //  WITH STROKE, LATIN CAPITAL LETTER
  0x028f: "Y", // , LATIN LETTER SMALL CAPITAL
  0x1d22: "Z", // , LATIN LETTER SMALL CAPITAL

  ["Ắ".codePointAt(0)!]: "A",
  ["Ấ".codePointAt(0)!]: "A",
  ["Ằ".codePointAt(0)!]: "A",
  ["Ầ".codePointAt(0)!]: "A",
  ["Ẳ".codePointAt(0)!]: "A",
  ["Ẩ".codePointAt(0)!]: "A",
  ["Ẵ".codePointAt(0)!]: "A",
  ["Ẫ".codePointAt(0)!]: "A",
  ["Ặ".codePointAt(0)!]: "A",
  ["Ậ".codePointAt(0)!]: "A",

  ["ắ".codePointAt(0)!]: "a",
  ["ấ".codePointAt(0)!]: "a",
  ["ằ".codePointAt(0)!]: "a",
  ["ầ".codePointAt(0)!]: "a",
  ["ẳ".codePointAt(0)!]: "a",
  ["ẩ".codePointAt(0)!]: "a",
  ["ẵ".codePointAt(0)!]: "a",
  ["ẫ".codePointAt(0)!]: "a",
  ["ặ".codePointAt(0)!]: "a",
  ["ậ".codePointAt(0)!]: "a",

  ["Ế".codePointAt(0)!]: "E",
  ["Ề".codePointAt(0)!]: "E",
  ["Ể".codePointAt(0)!]: "E",
  ["Ễ".codePointAt(0)!]: "E",
  ["Ệ".codePointAt(0)!]: "E",

  ["ế".codePointAt(0)!]: "e",
  ["ề".codePointAt(0)!]: "e",
  ["ể".codePointAt(0)!]: "e",
  ["ễ".codePointAt(0)!]: "e",
  ["ệ".codePointAt(0)!]: "e",

  ["Ố".codePointAt(0)!]: "O",
  ["Ớ".codePointAt(0)!]: "O",
  ["Ồ".codePointAt(0)!]: "O",
  ["Ờ".codePointAt(0)!]: "O",
  ["Ổ".codePointAt(0)!]: "O",
  ["Ở".codePointAt(0)!]: "O",
  ["Ỗ".codePointAt(0)!]: "O",
  ["Ỡ".codePointAt(0)!]: "O",
  ["Ộ".codePointAt(0)!]: "O",
  ["Ợ".codePointAt(0)!]: "O",

  ["ố".codePointAt(0)!]: "o",
  ["ớ".codePointAt(0)!]: "o",
  ["ồ".codePointAt(0)!]: "o",
  ["ờ".codePointAt(0)!]: "o",
  ["ổ".codePointAt(0)!]: "o",
  ["ở".codePointAt(0)!]: "o",
  ["ỗ".codePointAt(0)!]: "o",
  ["ỡ".codePointAt(0)!]: "o",
  ["ộ".codePointAt(0)!]: "o",
  ["ợ".codePointAt(0)!]: "o",

  ["Ứ".codePointAt(0)!]: "U",
  ["Ừ".codePointAt(0)!]: "U",
  ["Ử".codePointAt(0)!]: "U",
  ["Ữ".codePointAt(0)!]: "U",
  ["Ự".codePointAt(0)!]: "U",

  ["ứ".codePointAt(0)!]: "u",
  ["ừ".codePointAt(0)!]: "u",
  ["ử".codePointAt(0)!]: "u",
  ["ữ".codePointAt(0)!]: "u",
  ["ự".codePointAt(0)!]: "u",
};
